# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c305d23bfaabe668741acbc2ce269fa222fc199ac44847e66b9ab0643a96313f1980bfe12fe71d45f4647d5c7a6a1759961354885e574ccb452f8b74d991a4c9

test:
  secret_key_base: e3fca3499555d59cfefea99840816c51a50ae77d5d362f7430541ffd2884bda90d272b90c4a458ff6ad06a8bd97d1fa7e5ba8a6236b6eae2457dcdd74296d507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
