# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b76dd3d8dc499b80bfab5ce2107c5082e03992b1fb6727065259dfd9ea393421cbdf0c70ac20105261c3d1919983e7086c3303bba6a12449eff65ef0a85c626

test:
  secret_key_base: 831324b3514798b4bb8d53b54e2a14bf0be986c42bb857be6dbc936a6028a3380e774a8736a919945192b7fdb6ca26f7e73a6be513a44eb749309db0c02d99a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 
  
