# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2676e6a18a34f89ef9ce57e918413b6f926c5361301c1f8369e50a229594311124d28871cb47d841dc36d4ab8599ccc8f56cc88811abe9ff2d5a059c2389972

test:
  secret_key_base: 4cdd9e7411bcad02fbd23c003fcfac47df4899fb7654306f9b460793c61a21b9fec53278734e2061b427510452727c7577742b47005e84d2e84183138806d587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
